### ISSUE TITLE
Support for ARM processors

### ISSUE THREAD

**Issue by rehatiel** [dendianugerah/reubah#11]
It has been requested on my channel that you consider support for ARM processors so that people can run this on devices like Raspberry Pis.  

Thank you for the consideration!  Great project!

**Comment by mitchross** [comment]
I was able to run the docker image on my RPI5 without issues. Is there anything specific that doesnt work?

**Comment by rehatiel** [comment]
Hmm, great question @mitchross, let me see if I can get my viewer in here!

**Comment by rehatiel** [comment]
Nevermind, looks like there was a mistake with my viewer, it's working great!  Thank you for checking up with me!
