### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Just4Link** [dendianugerah/reubah#5]
Hello, i fell instantly in love with reubah.

Are you planing a dark mode too?

**Comment by dendianugerah** [comment]
Thanks for the kind words! :D I'm glad you like Reubah. Dark mode is definitely planned and one of my top priorities.

I apologize if there haven't been many updates recently. I've been busy, but I'll be back to work on it soon

**Comment by danish-mehmood** [comment]
@dendianugerah  can i work on shipping the dark mode for the application ?

**Comment by dendianugerah** [comment]
@danish-mehmood 

Of course! Feel free to open a pull request. I was planning to work on it this weekend haha, but since you're interested in contributing, I'd be happy to focus on another feature—like adding support for more file formats in the converter.

**Comment by danish-mehmood** [comment]
> @danish-mehmood
> 
> Of course! Feel free to open a pull request. I was planning to work on it this weekend haha, but since you're interested in contributing, I'd be happy to focus on another feature—like adding support for more file formats in the converter.

@dendianugerah sure i will work on it during the weekend

**Comment by danish-mehmood** [comment]
@dendianugerah meanwhile kindly assign the issue to me
