### ISSUE TITLE
Maximum file size setting

### ISSUE THREAD

**Issue by gaojunbin** [dendianugerah/reubah#9]
Hi, how can we change the maximum input file size? (e.g. change from 32MB to 1GB)

**Comment by dendianugerah** [comment]
Hi! Currently, the maximum input file size needs to be adjusted directly in the code. However, I plan to increase the default limit :)

**Comment by gaojunbin** [comment]
Okay, I see. Thank you and looking forward to the update!

**Comment by dendianugerah** [comment]
Ah, I see, that’s a great idea! I’ll add it in the next update
